# Generated by Django 2.0.2 on 2018-02-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('males', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='male',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='male',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
