# Generated by Django 2.0.2 on 2018-02-20 11:42

from django.db import migrations, models
import males.models


class Migration(migrations.Migration):

    dependencies = [
        ('males', '0002_auto_20180220_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='male',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='male',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='male',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to="images/", width_field='width_field'),
        ),
    ]
