# Generated by Django 2.0.2 on 2018-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('males', '0003_auto_20180220_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='male',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='male',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='male',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
