# Generated by Django 2.0.2 on 2018-02-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('males', '0004_auto_20180220_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='male',
            name='content',
        ),
        migrations.RemoveField(
            model_name='male',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='male',
            name='title',
        ),
        migrations.RemoveField(
            model_name='male',
            name='updated',
        ),
    ]
